In [1]:
import pandas as pd
import numpy as np

In [4]:
# load the dataset

df = pd.read_csv("../data/raw/personality_dataset.csv")

In [5]:
df.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert

In [6]:
df.sample(10)

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
2447,2.0,No,9.0,6.0,No,10.0,6.0,Introvert
2332,0.0,No,5.0,3.0,No,14.0,7.0,Extrovert
672,0.0,No,7.0,4.0,No,6.0,6.0,Extrovert
678,6.0,Yes,2.0,1.0,Yes,1.0,1.0,Introvert
940,2.0,No,9.0,6.0,No,11.0,5.0,Extrovert
1374,5.0,Yes,3.0,2.0,Yes,2.0,2.0,Introvert
736,9.0,Yes,2.0,2.0,Yes,3.0,0.0,Introvert
2217,5.0,Yes,1.0,2.0,Yes,3.0,NaN,Introvert
2496,NaN,Yes,3.0,2.0,Yes,2.0,1.0,Introvert

In [7]:
# Dataset inspection

df.shape

(2900, 8)

In [8]:
# columns names

df.columns

Index(['Time_spent_Alone', 'Stage_fear', 'Social_event_attendance',
       'Going_outside', 'Drained_after_socializing', 'Friends_circle_size',
       'Post_frequency', 'Personality'],
      dtype='str')

In [9]:
# data types

df.dtypes

Time_spent_Alone             float64
Stage_fear                       str
Social_event_attendance      float64
Going_outside                float64
Drained_after_socializing        str
Friends_circle_size          float64
Post_frequency               float64
Personality                      str
dtype: object

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Time_spent_Alone           2837 non-null   float64
 1   Stage_fear                 2827 non-null   str
 2   Social_event_attendance    2838 non-null   float64
 3   Going_outside              2834 non-null   float64
 4   Drained_after_socializing  2848 non-null   str
 5   Friends_circle_size        2823 non-null   float64
 6   Post_frequency             2835 non-null   float64
 7   Personality                2900 non-null   str
dtypes: float64(5), str(3)
memory usage: 181.4 KB